apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.devtools.ksp'
apply plugin: 'dagger.hilt.android.plugin'

android {
    compileSdkVersion rootProject.compileSdkVersion

    defaultConfig {
        minSdkVersion rootProject.minSdkVersion
        targetSdkVersion rootProject.targetSdkVersion

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += ["room.schemaLocation":
                                      "$projectDir/schemas".toString()]
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_21.toString()
    }

    sourceSets {
        androidTest.assets.srcDirs += files("$projectDir/schemas".toString())
    }
    namespace 'jp.co.soramitsu.core_db'
}

ksp {
    arg("room.schemaLocation", "$projectDir/schemas")
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(":common")
    implementation libs.gson
    implementation libs.kotlin.stdlib.jdk7

    implementation libs.coroutines.core

    implementation libs.hilt.android
    ksp libs.hilt.compiler

    implementation libs.room.runtime
    implementation libs.room.ktx
    ksp libs.room.compiler

    androidTestImplementation libs.runner
    androidTestImplementation libs.rules
    androidTestImplementation libs.ext.junit

    androidTestImplementation libs.room.testing
    androidTestImplementation projects.testShared
    testImplementation libs.junit
    testImplementation projects.testShared
}
