package jp.co.soramitsu.featurestakingimpl.domain.validations.unbond

import jp.co.soramitsu.common.validation.Validation
import jp.co.soramitsu.common.validation.ValidationSystem
import jp.co.soramitsu.featurestakingimpl.domain.validations.NotZeroAmountValidation
import jp.co.soramitsu.featurestakingimpl.domain.validations.UnbondingRequestsLimitValidation
import jp.co.soramitsu.featurewalletapi.domain.validation.EnoughToPayFeesValidation

typealias UnbondFeeValidation = EnoughToPayFeesValidation<UnbondValidationPayload, UnbondValidationFailure>
typealias NotZeroUnbondValidation = NotZeroAmountValidation<UnbondValidationPayload, UnbondValidationFailure>
typealias UnbondLimitValidation = UnbondingRequestsLimitValidation<UnbondValidationPayload, UnbondValidationFailure>

typealias UnbondValidation = Validation<UnbondValidationPayload, UnbondValidationFailure>

typealias UnbondValidationSystem = ValidationSystem<UnbondValidationPayload, UnbondValidationFailure>
