apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace = 'jp.co.soramitsu.shared_features.core'
    compileSdkVersion rootProject.compileSdkVersion

    defaultConfig {
        minSdkVersion rootProject.minSdkVersion
        targetSdkVersion rootProject.targetSdkVersion
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_21.toString()
    }
}

dependencies {
    api libs.kotlin.stdlib.jdk7
    api "jp.co.soramitsu.fearless-utils:fearless-utils:1.0.121"
}
