apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace = 'jp.co.soramitsu.xcm'
    compileSdkVersion rootProject.compileSdkVersion

    defaultConfig {
        minSdkVersion rootProject.minSdkVersion
        targetSdkVersion rootProject.targetSdkVersion
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_21.toString()
    }
}

dependencies {
    api libs.kotlin.stdlib.jdk7
    api libs.coroutines.core
    api project(':core-api')
    api project(':runtime')
    implementation libs.gson

    testImplementation libs.junit
}
